project:
  type: website

execute:
  freeze: auto
  
website:
  title: "Tinashe the Data Scientist"
  site-url: "tinashemtapera.com"
  description: "Tinashe M. Tapera's official website"
  favicon: "assets/img/data-science.png"
  preview:
    timeout: 3600
  
  # navs
  page-navigation: true
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: News
        href: news.qmd
      - text: CV
        href: cv.qmd
      - text: Blog
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/TinasheMTapera
      - icon: twitter
        href: https://twitter.com/TaperaTinashe
      - icon: linkedin
        href: https://linkedin.com/TinasheMTapera
  
   #     href: 
   #   - icon: twitter
   #     href: 
  search:
    location: navbar
    type: overlay
    copy-button: true
  #footer
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "LICENSE"
        href: LICENSE
      - text: "View on Github"
        href: https://github.com/TinasheMTapera/TinasheMTapera.github.io
  #socials
  open-graph: true
  twitter-card: 
    site: "@TaperaTinashe"

format:
  html:
    theme: cosmo
    css: styles.css



