## Basic Configuration
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
baseurl = "/" 
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Tinashe M. Tapera"
title = "My Personal Website"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Tinashe M. Tapera"
intro = "Psychologist turned Data Scientist"
description = "Junior Neuroimaging Data Scientist at University of Pennsylvania. Musician, Zimbabwean, Christian, Believer in People."
authorimage = "COAS-GRAD-CEREMONY-2017-071.JPG"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "My Personal Portfolio Website"
keywords = "data,data science,psychology,r,rmarkdown"

## Social Accounts
[params.social]
github = "<username>"
instagram = "<username>"
xing = "<username>"
linkedin = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "<username>"
stackoverflow = "<username>"
email = "you@example.com"

## Extras
[params.extra]
copyright = "© 2018. Tinashe M. Tapera. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
    
[[menu.main]]
    name = "post"
    identifier = "post"
    weight = 300
    url = "/post/"
