## Basic Configuration
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
baseurl = "/" 
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Tinashe M. Tapera"
title = "Tinashe's Personal Website"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Tinashe M. Tapera"
intro = "Data-intensive psychologist"
description = "MSc Psychology graduate of Drexel University, with a focus in data science applications in psychology."
authorimage = "ZNmgkZSx_400x400.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "My Personal Portfolio Website"
keywords = "data,data science,psychology,r,rmarkdown"

## Social Accounts
[params.social]
github = "TinasheMTapera"
linkedin = "tinashemtapera"
twitter = "TaperaTinashe"
email = "tinashemtapera@gmail.com"

## Extras
[params.extra]
copyright = "© 2022. Tinashe M. Tapera. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = true
highlightjs = true

## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 100
    url = "/about/"
[[menu.main]]
    name = "blog"
    weight = 200
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "Curriculum Vitae"
    url = "/cv/tinashemtapera_cv.pdf"
    weight = 300
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
